286 : Add method in QueuingHelper class
OpenSRP/opensrp-plan-evaluator pull request #68
Opened 2020-08-13 12:22 UTC by rehammuzzamil

https://github.com/OpenSRP/opensrp-server-core/issues/286
Extension of MVP - breaking it down further into entities

2020-08-19 10:19 UTC, githengi requested changes

2020-08-19 10:19 UTC, githengi commented on src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java
> -	public void testEvaluatePlanEvaluatesConditions() {
Retain this test and just  amend the trigger TriggerType.EVENT_SUBMISSION .

Add a new test that unit tests TriggerType.PLAN_ACTIVATION does queue the jobs

2020-08-19 13:14 UTC, githengi commented on src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java
> +
Verify that queuing was invoked

2020-08-19 13:30 UTC, rehammuzzamil commented on src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java
> +
> Verify that queuing was invoked

Updated

2020-08-20 15:03 UTC, githengi approved these changes

2020-08-20 15:03 UTC, merged